applications/cart/urls.py
from django.urls import path
from . import views

app_name = "cart_app"

urlpatterns = [
    path('add/<slug>', views.add_to_cart, name='add-to-cart'),
    path('add-c/<slug>/<color>', views.add_to_cart_color, name='add-to-cart-color'),
    path('add-s/<slug>/<size>', views.add_to_cart_size, name='add-to-cart-size'),
    path('add-cs/<slug>/<color>/<size>', views.add_to_cart_color_size, name='add-to-cart-color-size'),
    path('add-from-wish/<slug>', views.add_to_cart_from_wish, name='add-to-cart-from-wish'),
    path('remove/<slug>', views.remove_from_cart, name='remove-to-cart'),
    path('remove-c/<slug>/<color>', views.remove_from_cart_c, name='remove-to-cart-color'),
    path('remove-sc/<slug>/<color>/<size>', views.remove_from_cart_sc, name='remove-to-cart-size-color'),
    path('remove-s/<slug>/<size>', views.remove_from_cart_s, name='remove-to-cart-size'),
    path('clean/', views.clean_cart, name='clean-cart'),
    path('order/', views.OrderSummaryView.as_view(), name='order'),
    path('order-pay/', views.OrderSummaryPay.as_view(), name='orderpay'),
    path('order-finish/', views.orderSummaryFinish, name='orderfinish'),
    path('order-send/', views.orderSummaryEnds, name='orderend'),
    path('vendo-admin-orders/', views.orderAdmin, name='orderadmin'),
    path('vendo-admin-orders/<pk>', views.orderAdminDetail, name='orderadmindetail'),
    path('vendo-admin-orders/r/<pk>', views.realizadoOrder, name='realizarorder'),
    path('vendo-admin-orders/re/<pk>', views.revisionOrder, name='revisionorder'),
    path('vendo-admin-orders/p/<pk>', views.orderAdminPrint, name='printorder'),
    path('vendo-admin-orders/s/<pk>', views.sendOrder, name='sendorder'),
    path('vendo-admin-orders/c/<pk>', views.completeOrder, name='completeorder'),
    path('vendo-admin-orders/d/<pk>', views.cancelOrder, name='cancelorder'),
    path('vendo-admin-orders/w/<pk>', views.whatsappOrder, name='whatsapporder'),

    path('delete/<slug>', views.delete_item, name='delete-to-cart'),
    path('delete-c/<slug>/<color>', views.delete_item_c, name='delete-to-cart-color'),
    path('delete-s/<slug>/<size>', views.delete_item_s, name='delete-to-cart-size'),
    path('delete-sc/<slug>/<color>/<size>', views.delete_item_sc, name='delete-to-cart-size-color'),
] 

applications/dashboard/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "dashboard_app"

urlpatterns = [
	path('miempresa/', views.dashboard, name='dashboard'),
    path('miempresa/editar-producto/<product_id>', views.editproduct, name='editproduct'),
    path('miempresa/eliminar-producto/<slug>', views.deleteproduct, name='deleteproduct'),
    path('miempresa/productos', views.dashproduct, name='dashprod'),
    path('miempresa/nuevo-producto', views.dashnewprod, name='newprod'),
    path('miempresa/servicios', views.dashboardservices, name='dashserv'),
    path('miempresa/catalogo', views.dashcatalogue, name='dashcatalogue'),
    path('miempresa/nuevo-catalogo', views.dashnewcatalogue, name='newcatalogue'),
    path('miempresa/editar-catalogo/<product_id>', views.editcatalogue, name='editcatalogue'),
    path('miempresa/eliminar-catalogo/<pk>', views.deletecatalogue, name='deletecatalogue'),
    path('miempresa/cuenta', views.dashsetting, name='settings')
]

applications/orders/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "orders_app"

urlpatterns = [
	path('pedidos', views.indexOrders, name="index"),
	path('pedidos/<slug>', views.SingleOrders.as_view(), name="single-orders"),
] 

applications/product/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "product_app"

urlpatterns = [
	path('', views.index, name="index"),
	path('productos', views.listproducts, name="list-products"),
	path('comentario/<slug>', views.newComment, name="comments"),
	path('menos100', views.lessProduct, name="less-products"),
	path('covid', views.covidProduct, name="virus-products"),
	path('empresas-delivery', views.ListCompanyDelivery.as_view(), name="delivery"),
	path('producto/<slug>', views.SingleProduct.as_view(), name="single-product"),
	path('sub-categoria/<slug>/<pk>', views.ListSubCategorys.as_view(), name="sub-categorys"),
	path('productos/<slug>/<pk>/', views.ListSubCatProducts.as_view(), name="sub-catproducts"),
	path('empresa/<slug>/<pk>/', views.ListCompanyProducts.as_view(), name="company-products"),
	path('uempresa/<slug>/<pk>/', views.ListUserCompanyProducts.as_view(), name="user-company-products"),
	path('search/', views.search, name='search'),
	path('planes/', views.plan, name='planes'),
	path('terms/', views.terms, name='terms'),
	path('contract/', views.contract, name='contract')
] 

applications/services/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "services_app"

urlpatterns = [
	path('servicios', views.listServices.as_view(), name="list-services"),
	path('Servicio/<slug>', views.SingleServices.as_view(), name="single-services"),
] 

applications/useradmin/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from . import views

app_name = "useradmin_app"

urlpatterns = [
	path('registrarse/', views.registerDefault, name="registrarse"),
    path('entrar/', views.loginDefault, name='entrar'),
    path('entrar-usuario/', views.loginUsuarios, name='loginusuario'),
    path('salir/', views.logoutUser, name='salir'),
    path('nueva-empresa/', views.registerCompany, name="registercompany"),
    path('nuevo-usuario/', views.registerPage, name="registerusuario"),
    path('entrar-miempresa/', views.loginPage, name='logincompany'),
    path('perfil/', views.perfil, name='perfil'),
] 

applications/wish/urls.py
from django.urls import path
from . import views

app_name = "wish_app"

urlpatterns = [
    path('add-wish/<slug>', views.add_to_whis, name='add_to_whis'),
    path('remove-wish/<slug>', views.remove_from_whis, name='remove-to-whis'),
    path('wish-list/', views.WishSummaryView.as_view(), name='wish'),
] 

vendoencasa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

handler500 = 'applications.product.views.handler500'
handler404 = 'applications.product.views.handler404'
handler403 = 'applications.product.views.handler403'
handler400 = 'applications.product.views.handler400'

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('', include('applications.product.urls')),
    re_path('', include('applications.cart.urls')),
    re_path('', include('applications.wish.urls')),
    re_path('', include('applications.useradmin.urls')),
    re_path('', include('applications.services.urls')),
    re_path('', include('applications.dashboard.urls')),
    re_path('', include('applications.orders.urls')),
    re_path('accounts/', include('allauth.urls')),
    re_path('login/', auth_views.LoginView.as_view(), name='login'),
    re_path('logout/', auth_views.LogoutView.as_view(next_page='logout')), 
    re_path('oauth/', include('social_django.urls', namespace='social')),
]

applications/dashboard/models.py
from django.db import models

# Create your models here.

applications/product/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'calification', 'imagef', 'images', 'imaget')

applications/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from applications.product.models import Company, Category, SubCategory, Products, DiscountCode, RegistrationCode
from applications.services.models import Services
from applications.useradmin.models import Profile
from applications.cart.models import Order
from applications.orders.models import OrdersProducts
from django.db.models import Count
from django.contrib.auth.models import User
from .forms import ProductForm, OrdersForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import (
	TemplateView, 
	ListView,
)
from .forms import CreateCompanyForm, CompanyForm
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db.models import Avg
from django.db.models import Sum

@login_required(login_url='useradmin_app:entrar')
def dashboard(request):
    iduser = request.user.id
    companysCount = Company.objects.select_related().count()
    productsCount = Products.objects.select_related().filter(user__id=iduser).count()
    servicesCount = Services.objects.select_related().count()
    usersCount = User.objects.select_related().count()
    showProducts = Products.objects.select_related()[:10]

    viewsprod = Products.objects.select_related('user').filter(user__id=iduser).aggregate(Sum('views'))
    sellprod = Order.objects.select_related().filter(items__user__id=iduser, status='Pagado').count()
    sellprodlist = Order.objects.select_related().filter(items__user__id=iduser, status='Pagado')[:10]

    return render(request, 'dash-escritorio.html', {'CompanysCount': companysCount, 'ProductsCount': productsCount, 'UsersCount': usersCount, 'ServicesCount': servicesCount, 'ShowProduct': showProducts, 'viewsprod': viewsprod, 'sellprod': sellprod, 'sellprodlist': sellprodlist})


@login_required(login_url='useradmin_app:entrar')
def dashnewprod(request):
    iduser = request.user.id
    countprod = Products.objects.all().filter(user__id=iduser).count()
    userprofile = get_object_or_404(Profile, pk=request.user.profile.id)
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
        formprod = form.save(commit=False)
        if formprod.pricePromo:
            formprod.imagef = request.FILES['imagef']
            formprod.user = request.user
            formprod.price = int(formprod.price)
            formprod.comissionPriceProd = int(( formprod.price * formprod.subCategory.category.commission ) / 100)
            formprod.available = True
            formprod.save()
            form.save_m2m()
            return redirect("dashboard_app:dashprod")
        else:
            formprod.imagef = request.FILES['imagef']
            formprod.user = request.user
            formprod.price = int(formprod.price)
            formprod.comissionPriceProd = int(( formprod.price * formprod.subCategory.category.commission ) / 100)
            formprod.available = True
            formprod.save()
            form.save_m2m()
            return redirect("dashboard_app:dashprod")

    return render(request,'dash-new-prod.html', {'form':form})


@login_required(login_url='useradmin_app:entrar')
def dashboardservices(request):
	data = {}
	return render(request,'dash-services.html', data)


@login_required(login_url='useradmin_app:entrar')
def editproduct(request, product_id):
    product_to_edit = get_object_or_404(Products, pk=product_id)
    fecha_pub = product_to_edit
    form = ProductForm(instance=product_to_edit)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product_to_edit)
        if form.is_valid():
            formprod = form.save(commit=False)
            if formprod.pricePromo:
                formprod.price = int(formprod.price)
                formprod.comissionPriceProd = int(( formprod.price * formprod.subCategory.category.commission ) / 100)
                formprod.save()
                form.save_m2m()
                return redirect("dashboard_app:dashprod")
            else:
                formprod.price = int(formprod.price)
                formprod.comissionPriceProd = int(( formprod.price * formprod.subCategory.category.commission ) / 100)
                formprod.save()
                form.save_m2m()
                return redirect("dashboard_app:dashprod")
        else:
            form = ProductForm(instance=product_to_edit)

    return render(request, "dash-edit-prod.html", {'form': form, 'product': product_to_edit, 'fechapub': fecha_pub})


@login_required(login_url='useradmin_app:entrar')
def deleteproduct(request, slug):
    product = get_object_or_404(Products, slug=slug)
    product.delete()
    return redirect('dashboard_app:dashprod')


@login_required(login_url='useradmin_app:entrar')
def dashproduct(request):
    iduser = request.user.id
    productlist = Products.objects.select_related('user').filter(user__id=iduser).order_by('-pub_date')
    countprod = Products.objects.select_related('user').filter(user__id=iduser).count()
    userprofile = get_object_or_404(Profile, pk=request.user.profile.id)
    paginator = Paginator(productlist, 9)

    page = request.GET.get('page')
    prodpage = paginator.get_page(page)

    context = {'productlist': prodpage, 'countprod': countprod, 'userprofile': userprofile, 'prodpage': prodpage}
    return render(request,'dash-prod.html', context)


@login_required(login_url='useradmin_app:entrar')
def dashsettingas(request):
    form = CreateCompanyForm(request.POST)
    company_form = CompanyForm(request.POST, request.FILES)
    context = {}
    return render(request,'dash-settings.html', context)


@login_required(login_url='useradmin_app:entrar')
def dashsetting(request):
    product_to_edit = get_object_or_404(User, pk=request.user.id)
    profile_to_edit = get_object_or_404(Profile, pk=request.user.profile.id)
    form = CreateCompanyForm(instance=product_to_edit)
    formp = CompanyForm(instance=profile_to_edit)
    if request.method == 'POST':
        form = CreateCompanyForm(request.POST, request.FILES, instance=product_to_edit)
        formp = CompanyForm(instance=profile_to_edit)
        if form.is_valid():
            form.save()
            formp.save()
            return redirect('dashboard_app:dashprod')
        else:
            form = CreateCompanyForm(instance=product_to_edit)
            formp = CompanyForm(instance=profile_to_edit)

    return render(request, "dash-settings.html", {'form': form, 'formp': formp, 'product': product_to_edit})


@login_required(login_url='useradmin_app:entrar')
def dashcatalogue(request):
    iduser = request.user.id
    productlist = OrdersProducts.objects.select_related('user').filter(user__id=iduser)
    countprod = OrdersProducts.objects.select_related('user').filter(user__id=iduser).count()
    userprofile = get_object_or_404(Profile, pk=request.user.profile.id)

    context = {'productlist': productlist, 'countprod': countprod, 'userprofile': userprofile}
    return render(request,'dash-catalogue.html', context)


@login_required(login_url='useradmin_app:entrar')
def dashnewcatalogue(request):
    iduser = request.user.id
    countprod = OrdersProducts.objects.all().filter(user__id=iduser).count()
    userprofile = get_object_or_404(Profile, pk=request.user.profile.id)
    form = OrdersForm(request.POST, request.FILES)
    if form.is_valid():
        formprod = form.save(commit=False)
        formprod.imagef = request.FILES['imagef']
        formprod.user = request.user
        formprod.available = True
        formprod.save()
        form.save_m2m()
        return redirect("dashboard_app:dashcatalogue")

        
    return render(request,'dash-new-catalogue.html', {'form':form})


@login_required(login_url='useradmin_app:entrar')
def editcatalogue(request, product_id):
    product_to_edit = get_object_or_404(OrdersProducts, pk=product_id)
    fecha_pub = product_to_edit
    form = ProductForm(instance=product_to_edit)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product_to_edit)
        if form.is_valid():
            form.save()
            return redirect('dashboard_app:dashcatalogue')
        else:
            form = ProductForm(instance=product_to_edit)

    return render(request, "dash-edit-catalogue.html", {'form': form, 'product': product_to_edit, 'fechapub': fecha_pub})


@login_required(login_url='useradmin_app:entrar')
def deletecatalogue(request, pk):
    product = get_object_or_404(OrdersProducts, pk=pk)
    product.delete()
    return redirect('dashboard_app:dashcatalogue')

applications/services/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.views.generic import (
	TemplateView, 
	ListView,
)
from .models import Services
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import get_template
from django.contrib.auth.models import User
from django.db.models import Count

class listServices(ListView):
	template_name = 'services.html'
	paginate_by = 40
	model = Services
	context_object_name = 'services'

class SingleServices(ListView):
	template_name = "single-services.html"
	context_object_name = 'singleServices'

	def get_queryset(self):
		id = self.kwargs['slug']
		lista = Services.objects.all().filter(
			slug=id,
		)
		return lista

applications/product/templates/covid.html
{% extends "index.html" %}

{% block content %}
	{% load static %}
	{% load thumbnail %}
	<div class="container-fluid product-container">
		<div class="container">
			<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 20px;">Covid-19</h3>
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 wrap-products-list">
				{% if covidProd %}
					{% for p in covidProd %}
						<div class="card text-left prod-item" style="border:none; padding: 10px;">
							<a href="{% url 'product_app:single-product' p.slug %}" class="thumbnail">
								{% if p.imagef.url == '' %}
									<img src="{% static 'img/default_thumbnail.jpg' %}">
								{% else %}
									{% thumbnail p.imagef "250x250" crop="center" as im %}
										<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
									{% endthumbnail %}
								{% endif %}
							</a>
							<div class="card-body" style="padding: 15px 0px;">
								<h2 class="card-title"><b>{{ p.price }}</b><span>L.</span></h2>
								<h5 class="card-title">{{ p.title }}</h5>
								<a href="{% url 'product_app:single-product' p.slug %}" class="btn">Comprar</a>
							</div>
						</div><!-- End Of Product -->
					{% endfor %}
				{% else %}
					<h3 class="text-center" style="padding: 100px 0px; font-size: 20px; width: 100% !important; margin: 0px auto;">No encontramos resultados</h3>
				{% endif %}
			</div>

			<nav id="pagination">
				<div class="btn-group" role="group" aria-label="Basic example">
					{% if is_paginated %}
						{% if page_obj.has_previous %}
							<a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
			            {% endif %}
			            {% for i in paginator.page_range %}
			                <a href="?page={{i}}" {% if page_obj.number == i %} class="btn btn-secondary active" {% else %} class="btn btn-secondary" {% endif %}>{{ i }}</a>
			            {% endfor %}
			            {% if page_obj.has_next %}
			            	<a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
			            {% endif %}
					{% endif %}
				</div>
			</nav>
		</div>
	</div>

{% endblock content %}

applications/product/templates/dash-prod.html
{% extends "dashboard.html" %}

{% block content %}
{% load static %}
{% load thumbnail %}

<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 20px; width: 100%; margin-top: 20px; font-size: 40px;">Productos Publicados</h3>

<div class="row">
	<div class="col-12 mt-3">
		<div class="row mb-3">
			<div class="col-6 text-left">
				<small>Tienes {{countprod}} productos</small>
			</div>
			<div class="col-6 text-right">
				<a href="{% url 'dashboard_app:newprod' %}" class="primaryAction btn">Agregar Producto</a>
			</div>
		</div>
		{% for prod in productlist %}
			<div class="card mb-3 p-2" style="background: #fff; box-shadow: 0px 4px 7px #cacaca; border-radius: 5px; border-bottom: 1px solid #ccc !important;">
				<div class="row no-gutters">
					<div class="col-12 col-sm-3 col-md-3 col-lg-2">
						{% thumbnail prod.imagef "150x150" crop="center" as im %}
							<div class="squere-prod" style="background: url({{ im.url }}) center center no-repeat; background-size: cover; padding-bottom: 100%; width: 100%;"></div>
						{% endthumbnail %}
						<!--<img src="{{ prod.imagef.url }}" class="card-img">-->
					</div>
					<div class="col-11 col-sm-8 col-md-8 col-lg-9">
						<div style="display: block; height: 100%; position: relative;">
							<div style="padding: 10px;">
								<a href="{% url "dashboard_app:editproduct" prod.id %}">
									{{prod.title}}
									{% if prod.pricePromo %}
										<span class="btn ml-3" style="font-size: 10px;">PROMOCIÓN</span>
									{% endif %}
									{% if prod.quantity == 0 %}
										<span class="btn ml-3" style="font-size: 10px;">NO HAY EN INVENTARIO</span>
									{% endif %}
								</a>
								<p class="card-text mb-0">
									{% if prod.pricePromo %}
										Precio: <b>{{ prod.absolute_price|floatformat:2 }}</b><span style="font-size: 14px;">L.</span>
										<span class="ml-2" style="text-decoration: line-through; font-weight: normal; color: #ccc !important;">{{ prod.price|floatformat:2 }}<span style="font-size: 14px;">L.</span></span>
									{% else %}
										Precio: <b>{{ prod.absolute_price|floatformat:2 }}</b><span style="font-size: 14px;">L.</span>
									{% endif %}
								</p>
								<p class="card-text mb-0">
									Código: {{prod.productCode}}
								</p>
								<p class="card-text mb-0">
									Categoría: {{prod.subCategory}}
								</p>
								<p class="card-text mb-0">
									Visualizaciones: {{prod.views}}
								</p>
								<a href="{% url 'product_app:single-product' prod.slug %}" style="margin-right: 10px; margin-top: 10px; display: block;" target="blank">Visualizar Producto</a>
							</div>
						</div>
					</div>
					<div class="col-1">
						<div style="display: block; height: 100%; position: relative;">
							<div style="width: 100%; height: auto; position: absolute; top: 50%; transform: translateY(-50%); padding: 0px; text-align: center;">
								<!--<a href="{% url 'dashboard_app:deleteproduct' prod.slug %}" class="btn"><i class="fa fa-trash"></i></a>-->
								<button type="button" class="btn" data-toggle="modal" data-target="#exampleModal{{prod.id}}"><i class="fa fa-trash"></i></button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal fade" id="exampleModal{{prod.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered">
					<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Eliminar Producto</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						¿Estas seguro que quieres eliminarlo?
					</div>
					<div class="modal-footer">
						<a href="{% url 'dashboard_app:deleteproduct' prod.slug %}" class="btn"><i class="fa fa-trash"></i></a>
						<button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
					</div>
					</div>
				</div>
			</div><!-- End Of Modal -->
		{% endfor %}
	</div>
	<nav aria-label="Page navigation example" style="margin: 0px auto;">
		<ul class="pagination">
			{% if productlist.paginator.num_pages != 1 %}
				{% if productlist.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?page=1" aria-label="Previous">
					<span aria-hidden="true">&laquo;&laquo;</span>
					</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="?page={{ productlist.previous_page_number }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
				{% endif %}
				<li class="page-item"><a class="page-link">{{ productlist.number }} de {{ productlist.paginator.num_pages }}</a></li>

				{% if productlist.has_next %}
				<li class="page-item">
					<a class="page-link" href="?page={{ productlist.next_page_number }}" aria-label="Next">
					<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="?page={{ productlist.paginator.num_pages }}" aria-label="Next">
					<span aria-hidden="true">&raquo;&raquo;</span>
					</a>
				</li>
				{% endif %}
			{% endif %}
		</ul>
	</nav><!-- End of Pagination -->
</div>
{% endblock content %}

applications/product/templates/delivery.html
{% extends "index.html" %}

{% block content %}
	{% load static %}
	<div class="container-fluid product-container">
		<div class="container">
			<div class="row" style="margin-bottom: 40px;">
				<form class="input-group" action="/search/" method='GET'>
					<input type="search" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Buscar Empresa..." name="search-field" style="outline: none; border-top: 1px solid #f3f3f3 !important; border-bottom: 1px solid #f3f3f3 !important;" value="{{ request.GET.search }}">
					<div class="input-group-postpend">
						<button class="btn btn-outline-success" type="submit">
							<i class="fa fa-search"></i>
						</button>
					</div>
				</form>
			</div>
			<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 20px;">Lista de Empresas</h3>
			<div class="row  wrap-products-list">
				<table class="table table-hover w-100" style="margin-top: 30px;">
					<thead>
						<tr>
						<th scope="col">#</th>
						<th scope="col">Empresa</th>
						<th scope="col">Teléfono</th>
						<th scope="col">Dirección</th>
						</tr>
					</thead>
					<tbody>
						{% for delivery in delivery  %}
							<tr>
								<th scope="row">{{delivery.id}}</th>
								<td><a href="{% url 'product_app:company-products' delivery.slug delivery.id %}" style="width: max-content;">{{delivery.name}}</a></td>
								<td>{{delivery.phone}}</td>
								<td>{{delivery.address}}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>

			<nav id="pagination">
				<div class="btn-group" role="group" aria-label="Basic example">
					{% if is_paginated %}
						{% if page_obj.has_previous %}
							<a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
			            {% endif %}
			            {% for i in paginator.page_range %}
			                <a href="?page={{i}}" {% if page_obj.number == i %} class="btn btn-secondary active" {% else %} class="btn btn-secondary" {% endif %}>{{ i }}</a>
			            {% endfor %}
			            {% if page_obj.has_next %}
			            	<a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
			            {% endif %}
					{% endif %}
				</div>
			</nav>
		</div>
	</div>

{% endblock content %}

applications/product/templates/list-cats-header.html
{% for cheader in catsheader %}
	<option value="{{cheader.id}}">{{cheader.name}}</option>
{% endfor %}