applications/product/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "product_app"

urlpatterns = [
	path('', views.index, name="index"),
	path('productos', views.listproducts, name="list-products"),
	path('comentario/<slug>', views.newComment, name="comments"),
	path('menos100', views.lessProduct, name="less-products"),
	path('covid', views.covidProduct, name="virus-products"),
	path('empresas-delivery', views.ListCompanyDelivery.as_view(), name="delivery"),
	path('producto/<slug>', views.SingleProduct.as_view(), name="single-product"),
	path('sub-categoria/<slug>/<pk>', views.ListSubCategorys.as_view(), name="sub-categorys"),
	path('productos/<slug>/<pk>/', views.ListSubCatProducts.as_view(), name="sub-catproducts"),
	path('empresa/<slug>/<pk>/', views.ListCompanyProducts.as_view(), name="company-products"),
	path('uempresa/<slug>/<pk>/', views.ListUserCompanyProducts.as_view(), name="user-company-products"),
	path('search/', views.search, name='search'),
	path('planes/', views.plan, name='planes'),
	path('terms/', views.terms, name='terms'),
	path('contract/', views.contract, name='contract')
] 

vendoencasa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

handler500 = 'applications.product.views.handler500'
handler404 = 'applications.product.views.handler404'
handler403 = 'applications.product.views.handler403'
handler400 = 'applications.product.views.handler400'

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('', include('applications.product.urls')),
    re_path('', include('applications.cart.urls')),
    re_path('', include('applications.wish.urls')),
    re_path('', include('applications.useradmin.urls')),
    re_path('', include('applications.services.urls')),
    re_path('', include('applications.dashboard.urls')),
    re_path('', include('applications.orders.urls')),
    re_path('accounts/', include('allauth.urls')),
    re_path('login/', auth_views.LoginView.as_view(), name='login'),
    re_path('logout/', auth_views.LogoutView.as_view(next_page='logout')), 
    re_path('oauth/', include('social_django.urls', namespace='social')),
]

templates/home.html
{% extends "index.html" %}
{% block content %}
	{% load static %}
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	  	<ol class="carousel-indicators">
	    	<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	    	<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	    	<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	  	</ol>
	  	<div class="carousel-inner">
	    	<div class="carousel-item active">
	      		<img src="{% static 'img/topslide1.png' %}" class="d-block w-100">
	    	</div>
	    	<div class="carousel-item">
	      		<img src="{% static 'img/topslide2.png' %}" class="d-block w-100">
	    	</div>
	    	<div class="carousel-item">
	      		<img src="{% static 'img/topslide3.png' %}" class="d-block w-100">
	    	</div>
	  	</div>
	  	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	    	<i class="fa fa-arrow-circle-left"></i>
	  	</a>
	  	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	    	<i class="fa fa-arrow-circle-right"></i>
	  	</a>
	</div><!-- End Of Slider -->


	<div id="sliderads" class="carousel slide" data-ride="carousel">
	  	<ol class="carousel-indicators">
	    	<li data-target="#sliderads" data-slide-to="0" class="active"></li>
	    	<li data-target="#sliderads" data-slide-to="1"></li>
	    	<li data-target="#sliderads" data-slide-to="2"></li>
	  	</ol>
	  	<div class="carousel-inner">
	    	<div class="carousel-item active">
	      		<img src="{% static 'img/promoslide1.png' %}" class="d-block w-100">
	    	</div>
	    	<div class="carousel-item">
	      		<img src="{% static 'img/promoslide2.png' %}" class="d-block w-100">
	    	</div>
			l
	    	<div class="carousel-item">
	      		<img src="{% static 'img/promoslide3.png' %}" class="d-block w-100">
	    	</div>
	  	</div>
	  	<a class="carousel-control-prev" href="#sliderads" role="button" data-slide="prev">
	    	<i class="fa fa-arrow-circle-left"></i>
	  	</a>
	  	<a class="carousel-control-next" href="#sliderads" role="button" data-slide="next">
	    	<i class="fa fa-arrow-circle-right"></i>
	  	</a>
	</div><!-- End Of Slider Ads -->

	<div class="container-fluid list-cats">
		<div class="container">
			{% if listCategorys %}
				<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 10px;">Categorías</h3>
	    		<div class="container-fluid catslider" style="padding: 0px; margin: 0px;">
				    {% for cat in listCategorys %}
				        <div class="card text-left" style="padding: 5px; border: none;">
				        	<a href="{% url 'product_app:sub-categorys' cat.slug cat.id %}" class="linkitem thumbnail" style="border: none; border-radius: 0;">
				        		{% if cat.icono.url != '' %}
									<img src="{{ cat.icono.url }}" class="img-responsive thumbnail" style="border-radius: 0;">
								{% else %}
									<img src="{% static 'img/categoria.jpg' %}" class="img-responsive thumbnail" style="border-radius: 0;">
								{% endif %}
								<h5 class="card-title" style="padding: 15px 0px 0px 0px;">{{ cat.name }}</h5>
				        	</a>
				        </div><!-- End Of item -->
					{% endfor %}
				</div><!-- End Of Categorias -->
			{% endif %}

			{% if newProd %}
				<div class="fluid-cotainer" style="padding: 0px; margin: 15px 0px;">
				  	<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 10px;">Novedades</h3>
				  	<div class="container-fluid catslider" style="padding: 0px; margin: 0px;">
					    {% for nprod in newProd %}
							<div class="card text-left" style="border: none !important; padding: 5px;">
				  				<a href="{% url 'product_app:single-product' nprod.slug %}" class="thumbnail" style="border: none !important; border-radius: 0;">
									{% if nprod.imagef.url == '' %}
										<img src="{% static 'img/default_thumbnail.jpg' %}" style="border-radius: 0;">
									{% else %}
										<img src="{{ nprod.imagef.url }}" style="border-radius: 0;">
									{% endif %}
								</a>
								<div class="card-body" style="padding: 15px 0px 0px 0px;">
									<h2 class="card-title"><b>{{ nprod.price }}</b><span>L.</span></h2>
									<h5 class="card-title" style="color: #343a40;">{{ nprod.title }}</h5>
								</div>
				  			</div><!-- End Of item -->
						{% endfor %}
					</div>
				</div><!-- End Of Novedades -->
			{% endif %}

			{% if newProd %}
				<div class="fluid-cotainer" style="margin: 15px 0px; padding: 0px;">
				  	<h3 class="text-left" style="border-bottom: 1px solid #ccc; padding-bottom: 10px;">Más Buscados</h3>
				  	<div class="container-fluid catslider" style="padding: 0px; margin: 0px;">
					    {% for nprod in newProd %}
							<div class="card text-left" style="border: none !important; padding: 5px; border: none !important;">
				  				<a href="{% url 'product_app:single-product' nprod.slug %}" class="thumbnail" style="border: none !important; border-radius: 0;">
									{% if nprod.imagef.url == '' %}
										<img src="{% static 'img/default_thumbnail.jpg' %}" style="border-radius: 0;">
									{% else %}
										<img src="{{ nprod.imagef.url }}" style="border-radius: 0;">
									{% endif %}
								</a>
								<div class="card-body" style="padding: 15px 0px 0px 0px;">
									<h2 class="card-title"><b>{{ nprod.price }}</b><span>L.</span></h2>
									<h5 class="card-title" style="color: #343a40;">{{ nprod.title }}</h5>
								</div>
				  			</div><!-- End Of item -->
						{% endfor %}
					</div>
				</div><!-- End Of Mas Buscados -->
			{% endif %}
		</div>
	</div><!-- End Of Sliders -->

{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/page/favicon.png' %}">
    <meta name="description" content="Plataformas de ventas online con entregas a domicilio." />
    <meta property="og:image" content="/img/miniatura.png">
    <meta name="keywords" content="Honduras, Ventas, Tienda, Tienda en linea, Ecommerce, marketplace, vendo en casa, home office" />

	<title>Vendo en Casa</title>

	<!-- Styles -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>
<body>
	<header class="container-fluid fixed-top">
        <div class="pos-f-t">
		  	<div class="collapse" id="navbarToggleExternalContent">
		    	<div class="p-4">
		    		<ul>
		    			<li><a href="/">Inicio</a></li>
		    			<li><a href="/productos">Productos</a></li>
		    			<li><a href="/planes">Quiero Vender Desde Casa</a></li>
		    			<li><a href="#">Contáctanos</a></li>
		    		</ul>
		    	</div>
		  	</div>
		  	<nav class="navbar navbar-dark" data-aos="fade-down" data-aos-duration="700">
		  		<div class="row">
		  			<div class="col-6 col-md-3 col-lg-2 text-left float-left first">
		  				<a class="navbar-brand" href="/">
	                		<img src="{% static 'img/page/logo.png' %}">
	                	</a>
	                </div>

	                <div class="col-12 col-md-6 col-lg-8 col-form float-none second">
	                	<!--<form class="form-inline">
					    	<input class="form-control" type="search" placeholder="Search">
					    	<button class="btn btn-outline-success" type="submit">
					    		<i class="fa fa-search"></i>
					    	</button>
					    </form>-->
					    <form class="input-group" action="/search/" method='GET'>
						    <div class="input-group-prepend">
							    <select class="custom-select" name="search-category">
							    	<option selected value="">Categorías</option>
							    	<option value="1">Hogar</option>
							    	<option value="2">Comida</option>
							    	<option value="3">Deportes</option>
							    	<option value="4">Tecnologia</option>
							    	<option value="5">Cuidado Personal</option>
							    	<option value="6">Musica</option>
							    </select>
						    </div>
						    <input type="search" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Buscar..." name="search-field" style="outline: none; border-top: 1px solid #f3f3f3 !important; border-bottom: 1px solid #f3f3f3 !important;">
						    <div class="input-group-postpend">
						    	<button class="btn btn-outline-success" type="submit">
									<i class="fa fa-search"></i>
								</button>
						    </div>
						</form>
	                </div>
	                
	                <div class="col-6 col-md-3 col-lg-2 text-right float-right third ">
	                	<a class="navbar-car" href="/">
			                <i class="fa fa-shopping-cart"></i>
			            </a>
			            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
				      		<i class="fa fa-bars"></i>
				    	</button>
	                </div>
		  		</div>
		  	</nav>
		</div>
	</header><!-- End Of Header -->

	{% block content %}
	{% endblock %}

	<footer class="container-fluid bg-dark">
		<div class="container">

			<div class="row menufooter">
				<ul>
					<li><a href="/">Inicio</a></li>
		    		<li><a href="/productos">Productos</a></li>
		    		<li><a href="/planes">Quiero Vender Desde Casa</a></li>
		    		<li><a href="#">Contáctanos</a></li>
				</ul>
			</div>
			
			<div class="row social" style="padding: 25px 0px;">
				<ul>
					<li>
						<a href="https://www.facebook.com/vendoencasahn/"><i class="fa fa-facebook"></i></a>
					</li>
					<li>
						<a href="https://www.instagram.com/vendoencasa/"><i class="fa fa-instagram"></i></a>
					</li>
				</ul>
			</div>
			<!--<div class="row row-cols-1 row-cols-md-3">
				<div class="col"></div>
			</div>-->
			<div class="row copy" style="border-top: 1px solid #ccc;">
				<div class="col-xl-12 text-center">
                    <p class="copy_right text-center"></p>
                    <p style="color: #ccc;">Copyright ©<script>document.write(new Date().getFullYear());</script> <a href="https://www.studiomorebi.com"> Studio Morebi</a> Todos los Derechos Reservados</p>
                </div>
			</div>
		</div>
	</footer><!-- End Of Footer -->

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>

	<script>
		$('.catslider').slick({
		    dots: false,
		    infinite: true,
		    speed: 300,
		    slidesToShow: 6,
		    slidesToScroll: 6,
		    responsive: [
		      {
		        breakpoint: 1024,
		        settings: {
		          slidesToShow: 5,
		          slidesToScroll: 5,
		          infinite: true,
		          dots: false
		        }
		      },
			  {
		        breakpoint: 900,
		        settings: {
		          slidesToShow: 4,
		          slidesToScroll: 4,
		          infinite: true,
		          dots: false
		        }
		      },
		      {
		        breakpoint: 600,
		        settings: {
		          slidesToShow: 3,
		          slidesToScroll: 3
		        }
		      },
		      {
		        breakpoint: 480,
		        settings: {
		          slidesToShow: 2,
		          slidesToScroll: 2
		        }
		      }
		    ]
	  	});

		$('.slider-for').slick({
			slidesToShow: 1,
			slidesToScroll: 1,
			arrows: false,
			fade: true,
			asNavFor: '.slider-nav',
				autoplay: true
		});
		$('.slider-nav').slick({
			slidesToShow: 3,
			slidesToScroll: 1,
			asNavFor: '.slider-for',
			dots: false,
			centerMode: true,
			focusOnSelect: true

		});
	</script>

	<!-- Bootstrap -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script>
		AOS.init();
	</script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163598705-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-163598705-1');
	</script>
</body>
</html>

templates/search.html
{% extends "index.html" %}

{% block content %}
	{% load static %}
	<div class="container-fluid search-container">
		<div class="container">
			<h4 style="text-align: left; padding-bottom 15px; margin-bottom: 25px; font-size: 16px; color: #ccc;">
				{% if querytext %}
					resultados para: <b>{{ querytext }}</b>. <b>{{ count|length }}</b> resultados.
				{% else %}
					resultados de busqueda. <b>{{ count|length }}</b> resultados.
				{% endif %}
			</h4>
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 wrap-products-list">
				{% if contacts %}
					{% for s in contacts %}
						<div class="card text-left prod-item" style="border:none; padding: 10px;">
							<a href="{% url 'product_app:single-product' s.slug %}" class="thumbnail">
								{% if s.imagef.url == '' %}
									<img src="{% static 'img/default_thumbnail.jpg' %}">
								{% else %}
									<img src="{{ s.imagef.url }}">
								{% endif %}
							</a>
							<div class="card-body" style="padding: 15px 0px;">
								<h2 class="card-title"><b>{{ s.price }}</b><span>L.</span></h2>
								<h5 class="card-title">{{ s.title }}</h5>
								<a href="{% url 'product_app:single-product' s.slug %}" class="btn">Comprar</a>
							</div>
						</div><!-- End Of Product -->
					{% endfor %}
				{% else %}
					<h3 class="text-center" style="padding: 100px 0px; font-size: 20px; width: 100% !important; margin: 0px auto;">No encontramos resultados</h3>
				{% endif %}
			</div>

			<nav aria-label="Page navigation example" >
				<ul class="pagination">
					{% if contacts.paginator.num_pages != 1 %}
						{% if contacts.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?page=1" aria-label="Previous"><span aria-hidden="true">&laquo;&laquo;</span></a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ contacts.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
							</li>
						{% endif %}
							<li class="page-item"><a class="page-link">{{ contacts.number }} de {{ contacts.paginator.num_pages }}</a></li>
						{% if contacts.has_next %}
							<li class="page-item">
								<a class="page-link" href="?page={{ contacts.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ contacts.paginator.num_pages }}" aria-label="Next"><span aria-hidden="true">&raquo;&raquo;</span></a>
							</li>
						{% endif %}
					{% endif %}
				</ul>
			</nav><!-- End of Pagination -->


			<section>
				{% if contacts %} 
					<p class="contactss_len">contactss found: {{ contacts|length }}.</p>
					<ul> 
						{% for contactss in contacts %} 
							<li><a href="{% url 'translations' contactss.id %}">{{ contactss.title }}</a> </li>
						{% endfor %}
					</ul>
					{% elif contacts == None %}
						<p id="error_message">You left the form empty</p>
					{% else %} 
						<p id="error_message">Nothing found</p>
				{% endif %}
			</section>

		</div>
	</div>

{% endblock content %}